export const states = [
    "Andhra Pradesh",
"Arunachal Pradesh",
"Uttar Pradesh",
];
/*
export const states = [
    "Andhra Pradesh",
"Arunachal Pradesh",
"Assam",
"Bihar",
"Chhattisgarh",
"Goa",
"Gujarat",
"Haryana",
"Himachal Pradesh",
"Jammu & Kashmir",
"Jharkhand",
"Karnataka",
"Kerala",
"Madhya Pradesh",
"Maharashtra",
"Manipur",
"Meghalaya",
"Mizoram",
"Nagaland",
"Orissa",
"Punjab",
"Rajasthan",
"Sikkim",
"Tamil Nadu",
"Telangana",
"Tripura",
"Uttar Pradesh",
"Uttarakhand",
"West Bengal "
];
*/
export const districts = [
    ["Anantapur",
        "Chittoor",
        "East Godavari",
        "Guntur",
        "Krishna",
        "Kurnool",
        "Prakasam",
        "Srikakulam",
        "Sri Potti Sriramulu Nellore",
        "Visakhapatnam",
        "Vizianagaram",
        "West Godavari",
        "Kadapa (Cuddapah)"
    ], 
    [
        "Anjaw",
        "Changlang",
        "Dibang Valley",
        "East Kameng",
        "East Siang",
        "Kamle",
        "Kra Daadi",
        "Kurung Kumey",
        "Lepa Rada",
        "Lohit",
        "Longding",
        "Lower Dibang Valley",
        "Lower Siang",
        "Lower Subansiri",
        "Namsai",
        "Pakke Kessang",
        "Papum Pare"
    ]
    
    , ["Agra",
"Aligarh",
"Allahabad",
"Ambedkar Nagar",
"Amethi",
"Amroha",
"Auraiya",
"Azamgarh",
"Baghpat",
"Bahraich",
"Ballia",
"Balrampur",
"Banda",
"Barabanki",
"Bareilly",
"Basti",
"Bhadohi",
"Bijnor",
"Budaun",
"Bulandshahr",
"Chandauli",
"Chitrakoot",
"Deoria",
"Etah",
"Etawah",
"Faizabad",
"Farrukhabad",
"Fatehpur",
"Firozabad",
"Gautam Buddha Nagar",
"Ghaziabad",
"Ghazipur",
"Gonda",
"Gorakhpur",
"Hamirpur",
"Hapur",
"Hardoi",
"Hathras",
"Jalaun",
"Jaunpur",
"Jhansi",
"Kannauj",
"Kanpur Dehat",
"Kanpur Nagar",
"Kanshiram Nagar",
"Kaushambi",
"Kushinagar (Padrauna)",
"Lakhimpur - Kheri",
"Lalitpur",
"Lucknow",
"Maharajganj",
"Mahoba",
"Mainpuri",
"Mathura",
"Mau",
"Meerut",
"Mirzapur",
"Moradabad",
"Muzaffarnagar",
"Pilibhit",
"Pratapgarh",
"RaeBareli",
"Rampur",
"Saharanpur",
"Sambhal (Bhim Nagar)",
"Sant Kabir Nagar",
"Shahjahanpur",
"Shamali (Prabuddh Nagar)",
"Shravasti",
"Siddharth Nagar",
"Sitapur",
"Sonbhadra",
"Sultanpur",
"Unnao",
"Varanasi"]]; 